package com.hyperchip.user.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Entity representing a user's address in the system.
 * Stores multiple addresses per user (home, work, etc.) with soft delete and default flags.
 */
@Entity
@Table(name = "user_addresses")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Address {

    /**
     * Primary key for Address entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Many-to-One relationship with UserDtls.
     * Each address belongs to a single user.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private UserDtls user;

    /**
     * Label for the address to help users identify it easily.
     * Example: "Home", "Work", "Parents".
     */
    private String label;

    /**
     * Full address lines.
     * Line1 and Line2 with maximum length of 500 characters.
     */
    @Column(name = "address_line1", length = 500)
    private String addressLine1;

    @Column(name = "address_line2", length = 500)
    private String addressLine2;

    // City of the address
    private String city;

    // State of the address
    private String state;

    // Postal code / ZIP code of the address
    private String pincode;

    // Country of the address
    private String country;

    // Optional email contact for the address
    private String email;

    /**
     * Name of the contact person for deliveries.
     * Stored as String to support special characters, leading zeros, etc.
     */
    private String contactName;

    /**
     * Phone number of the contact person for deliveries.
     * Stored as String to support '+', leading zeros, and varying lengths.
     */
    private String contactPhone;

    /**
     * Indicates whether this address is the default for checkout.
     */
    @Column(name = "is_default")
    private Boolean isDefault = false;

    /**
     * Soft delete flag.
     * True means address is logically deleted but still present in database.
     */
    private Boolean deleted = false;

    /**
     * Timestamp for when the address was created.
     * Automatically set before inserting a new row.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Timestamp for the last update of the address.
     * Automatically updated whenever the row is updated.
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt = LocalDateTime.now();

    /**
     * Method executed before inserting a new Address row.
     * Purpose:
     * - Sets createdAt and updatedAt to current time.
     * - Ensures deleted and isDefault flags are not null.
     */
    @PrePersist
    public void prePersist() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.deleted == null) this.deleted = false;
        if (this.isDefault == null) this.isDefault = false;
    }

    /**
     * Method executed before updating an existing Address row.
     * Purpose:
     * - Updates updatedAt timestamp to current time for audit/sorting purposes.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
