package com.hyperchip.user.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.time.LocalDateTime;

/**
 * Entity representing a contact message submitted by a user.
 * Stores messages, contact details, and metadata such as urgency and timestamp.
 */
@Entity
@Table(name = "contact_messages")
@Data // Lombok annotation to generate getters, setters, toString, equals, and hashCode
@Builder // Lombok annotation to enable builder pattern for easier object creation
@NoArgsConstructor // Lombok annotation to generate a no-args constructor
@AllArgsConstructor // Lombok annotation to generate a constructor with all fields
public class Contact {

    /**
     * Primary key for the Contact entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the person submitting the message.
     */
    private String name;

    /**
     * Email of the person submitting the message.
     */
    private String email;

    /**
     * Phone number of the person submitting the message.
     * Stored as String to support '+', leading zeros, and varying lengths.
     */
    private String phone;

    /**
     * Optional order ID if the contact message is related to a specific order.
     */
    private String orderId;

    /**
     * Subject/title of the message.
     */
    private String subject;

    /**
     * Main message content.
     * Maximum length is 4000 characters.
     */
    @Column(length = 4000)
    private String message;

    /**
     * Indicates whether the message is marked as urgent.
     * Defaults to false.
     */
    private Boolean urgent = false;

    /**
     * Timestamp of when the message was created.
     * Stored as Instant (UTC time).
     * Automatically set to current time when object is created.
     */
    @Column(name = "created_at", updatable = false)
    private Instant createdAt = Instant.now();

}

