# =========================
# Bootstrap Configuration
# =========================


spring.config.import=configserver:http://config-server:8888
eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka 

spring.application.name=auth-service
server.port=8084


spring.cloud.config.fail-fast=false
management.endpoints.web.exposure.include=health,info

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG

# Make gateway reachable from your browser (use localhost when testing locally)
user.service.sso.finish=http://localhost:8080/sso/finish