#....D:\Microservice\Ecommerce Projects\HyperchipConfigServer\application.properties ...#


# =========================
# Application
# =========================
spring.application.name=config-server
server.port=8888

# =========================
# Git Config Repository
# =========================
spring.cloud.config.server.git.uri=https://github.com/Raiha137/Hyperchip-Microservices.git
spring.cloud.config.server.git.search-paths=HyperchipConfigServer/hyperchip-config
spring.cloud.config.server.git.default-label=main

spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.timeout=20
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.refresh-rate=60

# =========================
# Actuator
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.config.enabled=false

# =========================
# Disable Eureka (correct)
# =========================
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false