# D:\Microservice\Ecommerce Projects\HyperchipAdmin\application.properties


# =========================
# Bootstrap Configuration
# =========================
# =========================
# Application Configuration
# =========================

spring.application.name=hyperchip-admin

# Try Config Server but do not fail startup if it's not available
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true

# Enable retry for config server lookups
spring.cloud.config.retry.enabled=true
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.max-attempts=10

# (Optional) you can keep config enabled true but not required
# spring.cloud.config.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always