# =========================
# Bootstrap Configuration of user-service application.properties
# =========================

# =========================
# Application
# =========================
server.port=8083
spring.application.name=user-service
spring.profiles.active=prod

# =========================
# Config Server
# =========================
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.enabled=true
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5



# =========================
# Eureka
# =========================
eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka

# =========================
# Server Forward Headers
# =========================
server.forward-headers-strategy=framework
server.use-forward-headers=true

# =========================
# Actuator
# =========================
management.endpoints.web.exposure.include=health,info