package com.hyperchip.master.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Entity class representing a Brand in the system.
 * Used to store brand information such as name, image, and status.
 * Implements soft delete and automatic timestamping for creation and update.
 */
@Entity
@Table(name = "brands")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Brand {

    /**
     * Primary key for the Brand entity.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the brand.
     * Must be unique and cannot be null. Maximum length: 150 characters.
     */
    @Column(nullable = false, unique = true, length = 150)
    private String name;

    /**
     * Optional image file name associated with the brand.
     * Stored as a String (typically the filename or path in storage).
     */
    @Column(name = "image_name")
    private String imageName;

    /**
     * Status flag indicating whether the brand is active or not.
     * Used to enable/disable brand visibility in the system.
     */
    private boolean active = true;

    /**
     * Soft delete flag.
     * When true, the brand is considered deleted without removing it from the database.
     */
    private boolean deleted = false;

    /**
     * Timestamp of when the brand record was created.
     * Automatically set when the entity is first persisted.
     * Cannot be updated manually after creation.
     */
    @Column(updatable = false, nullable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of when the brand record was last updated.
     * Automatically updated on every update to the entity.
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Method annotated with @PrePersist.
     * Called automatically by JPA before the entity is persisted for the first time.
     * Sets both createdAt and updatedAt timestamps to the current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    /**
     * Method annotated with @PreUpdate.
     * Called automatically by JPA before the entity is updated.
     * Updates the updatedAt timestamp to the current time.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
