package com.hyperchip.master.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Entity class representing a Category in the system.
 * Used to store category information for products.
 * Implements soft delete and automatic timestamping for creation and updates.
 */
@Entity
@Table(name = "categories")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category {

    /**
     * Primary key for the Category entity.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the category.
     * Must be unique and cannot be null. Maximum length: 150 characters.
     */
    @Column(nullable = false, unique = true, length = 150)
    private String name;

    /**
     * Soft delete flag.
     * When true, the category is considered deleted without removing it from the database.
     */
    private boolean deleted = false;

    /**
     * Timestamp of when the category record was created.
     * Automatically set when the entity is first persisted.
     * Cannot be updated manually after creation.
     */
    @Column(updatable = false, nullable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of when the category record was last updated.
     * Automatically updated on every update to the entity.
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Status flag indicating whether the category is active or not.
     * Used to enable/disable category visibility in the system.
     */
    private boolean active = true;
    @Column(name = "active_name")
    private String activeName;


    /**
     * Optional image file name associated with the category.
     * Stored as a String (typically the filename or path in storage).
     */
    private String imageName;

    /**
     * Method annotated with @PrePersist.
     * Called automatically by JPA before the entity is persisted for the first time.
     * Sets both createdAt and updatedAt timestamps to the current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    /**
     * Method annotated with @PreUpdate.
     * Called automatically by JPA before the entity is updated.
     * Updates the updatedAt timestamp to the current time.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
