package com.hyperchip.master.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * Entity class representing a Coupon in the system.
 * Stores coupon code, discount, validity, and associated user information.
 * Supports automatic timestamps for creation and updates.
 */
@Entity
@Table(name = "coupons")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Coupon {

    /**
     * Primary key for the Coupon entity.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique coupon code.
     * Cannot be null and max length is 50 characters.
     */
    @Column(nullable = false, unique = true, length = 50)
    private String code;

    /**
     * Discount percentage for this coupon.
     * Example: 10 means 10% discount.
     */
    @Column(nullable = false)
    private Double discountPercentage;

    /**
     * Expiry date of the coupon.
     * Can be null if the coupon has no expiry.
     */
    private LocalDateTime expiryDate;

    /**
     * Status flag indicating whether the coupon is active.
     */
    private boolean active = true;

    /**
     * Timestamp when the coupon was created.
     * Automatically set when the entity is first persisted.
     */
    private LocalDateTime createdAt;

    /**
     * Timestamp when the coupon was last updated.
     * Automatically updated on every entity update.
     */
    private LocalDateTime updatedAt;

    /**
     * User ID of the referrer who created or owns the coupon.
     * Cannot be null.
     */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /**
     * Optional field indicating if the coupon is assigned to a specific user.
     * Null means the coupon is global and not tied to a single user.
     */
    @Column(name = "assigned_user_id")
    private Long assignedUserId;

    /**
     * Method annotated with @PrePersist.
     * Called automatically by JPA before the entity is persisted for the first time.
     * Sets both createdAt and updatedAt timestamps to the current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    /**
     * Method annotated with @PreUpdate.
     * Called automatically by JPA before the entity is updated.
     * Updates the updatedAt timestamp to the current time.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
