package com.hyperchip.master.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Entity class representing a Product in the system.
 * Stores product details such as title, description, price, stock, category, brand, and images.
 * Supports soft delete, active status, and automatic timestamps for creation and updates.
 */
@Entity
@Table(name = "products")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Product {

    /**
     * Primary key for the Product entity.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the product.
     * Cannot be null and has a maximum length of 200 characters.
     */
    @Column(nullable = false, length = 200)
    private String title;

    /**
     * Detailed description of the product.
     * Stored as TEXT in the database.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Price of the product.
     * Cannot be null.
     */
    @Column(nullable = false)
    private Double price;

    // Uncomment if you want to store discount details
    // private Double discount; // percentage
    // private Double discountPrice; // calculated price after discount

    /**
     * Stock quantity available for the product.
     * Cannot be null.
     */
    @Column(nullable = false)
    private Integer stock;

    /**
     * Soft delete flag.
     * When true, the product is considered deleted without removing it from the database.
     */
    @Column(name = "deleted", nullable = false)
    private boolean deleted = false;

    /**
     * Status flag indicating whether the product is active.
     * Used to enable/disable product visibility in the system.
     */
    @Column(name = "active", nullable = false)
    private boolean active = true;

    /**
     * Many-to-one relationship to Category.
     * Eager fetch ensures category details are loaded along with the product.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "category_id")
    private Category category;

    /**
     * Many-to-one relationship to Brand.
     * Eager fetch ensures brand details are loaded along with the product.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "brand_id")
    private Brand brand;

    /**
     * List of additional images for the product.
     * Stored in a separate table "product_images" with product_id as foreign key.
     */
    @ElementCollection
    @CollectionTable(name = "product_images", joinColumns = @JoinColumn(name = "product_id"))
    @Column(name = "image_name")
    private List<String> images;

    /**
     * Thumbnail image for the product.
     * Usually used as the main display image.
     */
    @Column(name = "thumbnail")
    private String imageName;

    /**
     * Timestamp when the product was created.
     * Automatically set when the entity is first persisted.
     */
    @Column(updatable = false, nullable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the product was last updated.
     * Automatically updated on every entity update.
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Method annotated with @PrePersist.
     * Called automatically by JPA before the entity is persisted for the first time.
     * Sets both createdAt and updatedAt timestamps to the current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    /**
     * Method annotated with @PreUpdate.
     * Called automatically by JPA before the entity is updated.
     * Updates the updatedAt timestamp to the current time.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
