package com.hyperchip.master.model;

import com.hyperchip.common.dto.OfferDiscountType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Entity class representing an offer applied to a specific product.
 * Stores discount type, discount value, active status, and validity period.
 * Uses loose coupling by storing only productId instead of a full Product entity.
 */
@Entity
@Table(
        name = "product_offers",
        indexes = {
                // Index for faster lookup by product
                @Index(name = "idx_product_offer_product", columnList = "product_id"),
                // Index for faster lookup of active offers
                @Index(name = "idx_product_offer_active", columnList = "active")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProductOffer {

    /**
     * Primary key for the ProductOffer entity.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Product ID to which this offer applies.
     * Loose coupling used instead of direct Product object for flexibility and simplicity.
     */
    @Column(name = "product_id", nullable = false)
    private Long productId;

    /**
     * Type of discount applied.
     * Enum is stored as STRING in the database (e.g., PERCENTAGE, FIXED_AMOUNT).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "discount_type", nullable = false, length = 20)
    private OfferDiscountType discountType;

    /**
     * Discount value.
     * Precision 10, scale 2 allows up to 99999999.99 as value.
     */
    @Column(name = "discount_value", nullable = false, precision = 10, scale = 2)
    private BigDecimal discountValue;

    /**
     * Flag indicating if the offer is active.
     * Allows enabling/disabling the offer without deleting the record.
     */
    @Column(name = "active", nullable = false)
    private Boolean active = true;

    /**
     * Timestamp when the offer starts.
     * Can be null if the offer is immediately active.
     */
    @Column(name = "start_at")
    private Instant startAt;

    /**
     * Timestamp when the offer ends.
     * Can be null for offers with no expiry.
     */
    @Column(name = "end_at")
    private Instant endAt;

    /**
     * Timestamp when the offer was created.
     * Automatically set by Hibernate on entity creation.
     * Cannot be updated manually.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp when the offer was last updated.
     * Automatically updated by Hibernate on each update.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;
}
