package com.hyperchip.master.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

/**
 * Entity class representing a Referral Code in the system.
 * Stores unique referral codes linked to existing users.
 * Includes active status and automatic creation timestamp.
 */
@Entity
@Table(
        name = "referral_codes",
        indexes = {
                // Unique index for faster lookup by code
                @Index(name = "idx_referral_code_code", columnList = "code", unique = true),
                // Index for faster lookup by user ID
                @Index(name = "idx_referral_code_user", columnList = "user_id")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReferralCode {

    /**
     * Primary key for the ReferralCode entity.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * ID of the existing user who owns this referral code.
     * Cannot be null.
     */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /**
     * Unique referral code string.
     * Cannot be null and maximum length is 50 characters.
     */
    @Column(name = "code", nullable = false, unique = true, length = 50)
    private String code;

    /**
     * Status flag indicating whether the referral code is active.
     * Allows enabling/disabling referral codes without deleting them.
     */
    @Column(name = "active", nullable = false)
    private Boolean active = true;

    /**
     * Timestamp when the referral code was created.
     * Automatically set by Hibernate when the entity is first persisted.
     * Cannot be updated manually.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
}
