package com.hyperchip.master.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

/**
 * Entity class representing a reward for a referral.
 * Tracks which user referred whom, the referral code used, and the reward status.
 * Includes automatic creation timestamp and optional referred user email.
 */
@Entity
@Table(
        name = "referral_rewards",
        indexes = {
                // Index for faster lookup by referrer user
                @Index(name = "idx_ref_reward_referrer", columnList = "referrer_user_id"),
                // Index for faster lookup by referred user
                @Index(name = "idx_ref_reward_referred", columnList = "referred_user_id")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReferralReward {

    /**
     * Primary key for the ReferralReward entity.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User ID of the person who referred someone.
     * Cannot be null.
     */
    @Column(name = "referrer_user_id", nullable = false)
    private Long referrerUserId;

    /**
     * User ID of the person who was referred.
     * Cannot be null.
     */
    @Column(name = "referred_user_id", nullable = false)
    private Long referredUserId;

    /**
     * Referral code used for this referral.
     * Cannot be null. Max length 50 characters.
     */
    @Column(name = "referral_code", nullable = false, length = 50)
    private String referralCode;

    /**
     * Status of the referral reward.
     * Examples: PENDING_REWARD, COUPON_ISSUED, USED, EXPIRED.
     */
    @Column(name = "status", nullable = false, length = 30)
    private String status;

    /**
     * Timestamp when the referral reward was created.
     * Automatically set by Hibernate when the entity is first persisted.
     * Cannot be updated manually.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Optional email of the referred user.
     * Useful for notifications or record-keeping.
     */
    @Column(name = "referred_user_email")
    private String referredUserEmail;
}
