# D:\Microservice\Ecommerce Projects\HyperchipMaster\application.properties

# =========================
# Application
# =========================
spring.application.name=hyperchip-master
spring.profiles.active=prod
server.port=8086
# =========================
# Config Server
# =========================
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.enabled=false

# =========================
# Eureka
# =========================
eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka

# =========================
# Actuator
# =========================
management.endpoints.web.exposure.include=health,info