#....D:\Microservice\Ecommerce Projects\HyperchipConfigServer\hyperchip-config\hyperchip-admin.properties ....#


# =====================
# Application & Server
# =====================
spring.application.name=admin-service
server.port=8085


gateway.base.url=http://localhost:8080

# =====================
# Logging
# =====================
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=DEBUG

# =====================
# Database
# =====================
spring.datasource.url=jdbc:mysql://admin-mysql:3306/hyperchip_admin_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${ADMIN_DB_USER}
spring.datasource.password=${ADMIN_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Eureka

eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://discovery:8761/eureka


eureka.instance.hostname=${spring.application.name}
eureka.instance.prefer-ip-address=true


# =====================
# File Upload Settings
# =====================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Centralized upload directory (Windows)
upload.dir=/uploads
spring.web.resources.static-locations=classpath:/static/,file:/uploads/

# Make uploaded files accessible

# =====================
# Thymeleaf
# =====================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# =====================
# Service URLs=-0oki8====================
# =====================
# Service URLs (Updated for Docker Networking)
# =====================

user.service.url=http://api-gateway:8080
server.forward-headers-strategy=framework
api.base.url=http://localhost:8080/masters/api/admin
master.service.url=http://master-service:8086
product.service.url=http://master-service:8086
auth.service.url=http://auth-service:8084
order.service.url=http://order-service:8092

logging.level.com.yourpackage=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always

spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5
spring.cloud.config.retry.max-attempts=10

management.endpoints.web.exposure.include=health,info,env
management.endpoint.env.show-values=ALWAYS