spring:
  cloud:
    gateway:
      routes:
        - id: master-api
          uri: http://master-service:8086
          order: 1
          predicates:
            - Path=/api/masters/**
        - id: master-uploads
          uri: http://master-service:8086
          order: 2
          filters:
            - StripPrefix=0          # do not strip any path segments
            - PreserveHostHeader     # keep original Host header
          predicates:
            - Path=/uploads/**
