#Ecommerce Projects/HyperchipApiGateway/src/resources/application.properties

spring.config.import=configserver:http://config-server:8888
eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
spring.application.name=hyperchip-api-gateway
spring.cloud.config.enabled=true

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
